"""Browser interaction QA. Uses offline set_content by default, or CF_TEST_URL.
Offline mode does not claim to validate secure-origin GPU or IndexedDB behavior.
Requires Python playwright and a browser executable (CF_BROWSER, default chromium).
"""
from pathlib import Path
from playwright.sync_api import sync_playwright
import os,json,base64,zipfile,io
ROOT=Path(__file__).resolve().parents[1]
OUTPUT=ROOT/'docs'/'qa';OUTPUT.mkdir(parents=True,exist_ok=True)
results=[]
def check(name,condition,detail=None):
    if not condition: raise AssertionError(name+(': '+str(detail) if detail is not None else ''))
    results.append({'name':name,'passed':True});print('PASS',name)
with sync_playwright() as p:
    browser=p.chromium.launch(executable_path=os.environ.get('CF_BROWSER','/usr/bin/chromium'),headless=True,args=['--no-sandbox'])
    page=browser.new_page(viewport={'width':1600,'height':1000},device_scale_factor=1)
    errors=[];page.on('pageerror',lambda e:errors.append(str(e)))
    url=os.environ.get('CF_TEST_URL')
    if url:page.goto(url,wait_until='networkidle')
    else:page.set_content((ROOT/'dist/ChromaForge-Standalone.html').read_text(),wait_until='load',timeout=120000)
    page.wait_for_function('window.chroma?.ready===true',timeout=120000)
    page.wait_for_timeout(9000)
    mode=page.evaluate('chroma.renderer.mode')
    check('studio starts with an actual renderer',mode in ['WebGPU','WebGL2','CPU compatibility'],mode)
    check('four sample texture sets are exposed',page.locator('.set-row').count()==4)
    check('all 24 material assets are exposed',page.locator('[data-asset]').count()==24)
    page.screenshot(path=str(OUTPUT/'studio-dark.png'),full_page=True)
    page.evaluate("chroma.store.dispatch('project:set',{patch:{resolution:256}},'QA resolution')")
    page.wait_for_timeout(450)
    check('resolution changes replay the texture maps',page.evaluate('chroma.compositor.size===256&&chroma.compositor.outputs.get(chroma.setId).color.width===256'))
    page.evaluate("Object.assign(chroma.brush,{color:'#ff0055',size:.13,flow:1,hardness:1,pressure:false});chroma.setBrushColor('#ff0055')")
    pos=page.evaluate("(()=>{const r=chroma.uvRect(),b=document.querySelector('#viewport2d').getBoundingClientRect();return {x:b.x+r.x+r.size*.4,y:b.y+r.y+r.size*.5,width:r.size};})()")
    def uv_stroke(x1=.4,x2=.6,y=.5):
        pos=page.evaluate("(()=>{const r=chroma.uvRect(),b=document.querySelector('#viewport2d').getBoundingClientRect();return {x:b.x+r.x,y:b.y+r.y,size:r.size};})()")
        page.mouse.move(pos['x']+pos['size']*x1,pos['y']+pos['size']*y);page.mouse.down();page.mouse.move(pos['x']+pos['size']*x2,pos['y']+pos['size']*y,steps=8);page.mouse.up();page.wait_for_timeout(400)
    def pixel():return page.evaluate("[...chroma.compositor.outputs.get(chroma.setId).color.getContext('2d').getImageData(128,128,1,1).data]")
    before=pixel();uv_stroke();painted=pixel()
    check('pointer painting records editable pressure-aware strokes',page.evaluate("chroma.layer.strokes.length===1&&chroma.layer.strokes[0].points.length>2"))
    check('pointer painting changes actual texture pixels',painted[0]>245 and painted[1]<10 and painted[2]>70,painted)
    page.keyboard.press('Control+z');page.wait_for_timeout(450)
    check('keyboard undo restores original texture pixels',pixel()==before,(before,pixel()))
    page.keyboard.press('Control+Shift+z');page.wait_for_timeout(450)
    check('keyboard redo restores the stroke',pixel()==painted)
    page.evaluate("chroma.run('add-mask')");page.get_by_role('button',name='Black mask',exact=True).click();page.wait_for_timeout(400)
    check('black mask conceals the painted layer',pixel()==before,pixel())
    uv_stroke(.47,.53)
    check('painting a mask reveals existing material pixels',pixel()[0]>245 and pixel()[1]<10,pixel())
    check('mask strokes have their own target',page.evaluate("chroma.layer.strokes.at(-1).target==='mask'"))
    page.evaluate("chroma.run('remove-mask');chroma.setTool('erase')");uv_stroke(.47,.53)
    check('eraser removes paint without changing the base fill',pixel()==before,(before,pixel()))
    page.evaluate("chroma.setTool('paint')")
    b=page.locator('#viewport3d').bounding_box();page.mouse.move(b['x']+b['width']*.5,b['y']+b['height']*.48);page.mouse.down();page.mouse.move(b['x']+b['width']*.52,b['y']+b['height']*.48,steps=5);page.mouse.up();page.wait_for_timeout(400)
    check('3D surface painting records barycentric UV strokes',page.evaluate("chroma.store.operations.filter(o=>o.type==='stroke:add').length>=4"))
    page.locator('[data-asset="teal"]').click();page.wait_for_timeout(350)
    check('asset selection creates an editable procedural fill',page.evaluate("chroma.layer.type==='fill'&&chroma.layer.name==='Ocean enamel'"))
    page.locator('[data-prop-tab="layer"]').click()
    slider=page.locator('cf-slider[data-prop="roughness"]').locator('input[type="number"]');slider.fill('0.72');slider.press('Tab');page.wait_for_timeout(350)
    check('typed property editor updates the document',page.evaluate('Math.abs(chroma.layer.roughness-.72)<.001'))
    page.evaluate("chroma.run('duplicate-layer')");page.wait_for_timeout(250)
    check('duplicate layer creates a distinct identifier',page.evaluate("chroma.set.layers.at(-1).name.endsWith(' copy')&&chroma.set.layers.at(-1).id!==chroma.set.layers.at(-2).id"))
    page.evaluate("chroma.run('layer-down')");page.wait_for_timeout(100)
    check('layer reordering changes the stack',page.evaluate("chroma.set.layers.at(-2).id===chroma.layerId"))
    page.keyboard.press('F2');page.wait_for_timeout(350)
    check('3D-only layout expands the viewport',page.evaluate("chroma.view==='3d'&&document.querySelector('#viewport2d').clientWidth===0"))
    page.keyboard.press('F3');page.wait_for_timeout(250)
    check('2D-only layout is available',page.evaluate("chroma.view==='2d'"))
    page.keyboard.press('F1');page.wait_for_timeout(250)
    page.locator('#channel-view').select_option('roughness');page.wait_for_timeout(300)
    check('channel inspection changes the renderer mode',page.evaluate('chroma.renderer.settings.channel===2'))
    page.locator('#channel-view').select_option('material')
    page.keyboard.press('Control+k');page.locator('#command-search').fill('wireframe');page.wait_for_timeout(100)
    check('command palette filters executable commands',page.locator('[data-palette-command]').count()>=1)
    page.keyboard.press('Escape')
    page.locator('[data-side-tab="notes"]').click();page.locator('#note-text').fill('Review the edge finish');page.locator('[data-action="note-add"]').click()
    check('review notes are stored in the document',page.evaluate("chroma.store.state.comments.at(-1).text==='Review the edge finish'"))
    page.locator('[data-action="resolve-note"]').last.click()
    check('notes can be resolved',page.evaluate('chroma.store.state.comments.at(-1).resolved'))
    page.locator('[data-side-tab="layers"]').click()
    # Capture generated blobs in page memory; do not bypass browser download policies.
    page.evaluate("window.qaBlobs=[];URL.createObjectURL=b=>{qaBlobs.push(b);return 'blob:qa-placeholder'};HTMLAnchorElement.prototype.click=function(){}")
    page.evaluate("chroma.run('export')");page.locator('#export-scope').select_option('active');page.get_by_role('button',name='Export ZIP',exact=True).click()
    page.wait_for_function('qaBlobs.some(b=>b.type==="application/zip")',timeout=30000)
    encoded=page.evaluate("async()=>{const b=qaBlobs.find(b=>b.type==='application/zip');const a=new Uint8Array(await b.arrayBuffer());let s='';for(const v of a)s+=String.fromCharCode(v);return btoa(s);}")
    data=base64.b64decode(encoded);archive=zipfile.ZipFile(io.BytesIO(data));names=archive.namelist()
    check('texture export produces a valid ZIP with PNGs and manifest','manifest.json' in names and len([n for n in names if n.endswith('.png')])==5,names)
    check('PNG export contains actual PNG data',all(archive.read(n).startswith(b'\x89PNG\r\n\x1a\n') for n in names if n.endswith('.png')))
    manifest=json.loads(archive.read('manifest.json'));check('export manifest records the actual resolution',manifest['resolution']==256)
    page.evaluate("chroma.run('save')");page.wait_for_function("qaBlobs.some(b=>b.type==='application/json')")
    saved=page.evaluate("async()=>JSON.parse(await qaBlobs.find(b=>b.type==='application/json').text())")
    check('project export preserves editable operation history',saved['format']=='chromaforge' and len(saved['operations'])>10)
    page.evaluate("chroma.run('text-decal')");page.locator('#decal-text').fill('CHROMAFORGE');page.get_by_role('button',name='Add decal',exact=True).click();page.wait_for_timeout(400)
    check('text decal becomes an editable image layer',page.evaluate("chroma.layer.type==='decal'&&chroma.layer.image.startsWith('data:image/png')"))
    page.evaluate("chroma.run('theme')");page.wait_for_timeout(350)
    check('light theme switches without removing controls',page.evaluate("document.body.classList.contains('light')") and page.locator('.set-row').count()==4)
    page.screenshot(path=str(OUTPUT/'studio-light.png'),full_page=True)
    page.evaluate("chroma.run('theme');chroma.run('density')")
    check('comfortable density is selectable',page.evaluate("document.querySelector('.studio').classList.contains('comfortable')"))
    page.evaluate("chroma.run('density')")
    await_import="""async()=>{const file=new File(['v 0 0 0\\nv 1 0 0\\nv 0 1 0\\nvt 0 0\\nvt 1 0\\nvt 0 1\\nf 1/1 2/2 3/3'], 'triangle.obj',{type:'text/plain'});await chroma.importMesh([file]);return chroma.mesh.triangleCount;}"""
    check('mesh import replaces the active document with parsed geometry',page.evaluate(await_import)==1)
    check('browser completes without uncaught JavaScript exceptions',len(errors)==0,errors)
    result={'mode':mode,'loading':'served' if url else 'offline set_content','checks':results,'uncaughtErrors':errors,'indexedDBAvailable':page.evaluate('chroma.storageAvailable'),'secureContext':page.evaluate('isSecureContext')}
    (OUTPUT/'browser-results.json').write_text(json.dumps(result,indent=2));print(json.dumps({'checks':len(results),'renderer':mode,'errors':errors},indent=2))
    browser.close()
