import { readFileSync, writeFileSync, mkdirSync, existsSync, cpSync } from 'node:fs';
import { resolve, dirname, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const read = p => readFileSync(p, 'utf8');
const put = (p, s) => { mkdirSync(dirname(p), { recursive: true }); writeFileSync(p, s); };
/** Small deterministic bundler for this repository's named-import ESM subset.
 * No third-party compiler is required. Package outputs include their dependencies.
 * Unsupported import forms fail the build instead of silently producing bad code.
 */
export function bundle(entry, { esm = false } = {}) {
    const modules = new Map();
    function visit(path) {
        path = resolve(path);
        if (modules.has(path))
            return modules.get(path);
        const m = { id: modules.size, code: '', names: new Set() };
        modules.set(path, m);
        let code = read(path), ex = [];
        code = code.replace(/^import\s+\{([^}]+)\}\s+from\s+['"]([^'"]+)['"];?/gm, (_, bindings, spec) => { if (!spec.startsWith('.'))
            throw Error(`Non-relative import ${spec}`); const dep = visit(resolve(dirname(path), spec)); const props = bindings.trim().replace(/\s+as\s+/g, ':'); return `const {${props}}=require(${dep.id});`; });
        code = code.replace(/^export\s+\*\s+from\s+['"]([^'"]+)['"];?/gm, (_, spec) => { const dep = visit(resolve(dirname(path), spec)); for (const n of dep.names)
            m.names.add(n); return `Object.assign(exports,require(${dep.id}));`; });
        code = code.replace(/\bexport\s+(async\s+)?(function|class|const|let|var)\s+([\w$]+)/g, (_, asyncWord, kind, name) => { m.names.add(name); ex.push(name); return `${asyncWord ?? ''}${kind} ${name}`; });
        if (/^import\s/m.test(code) || /^export\s/m.test(code))
            throw Error(`Unsupported ESM syntax in ${path}`);
        m.code = code + '\n' + ex.map(n => `exports.${n}=${n};`).join('\n');
        return m;
    }
    const main = visit(entry);
    let out = `/* ChromaForge 0.1.0 · MIT · generated by scripts/build.js */\nconst __entry=(()=>{const modules={\n`;
    out += [...modules.entries()].map(([p, m]) => `${m.id}:(exports,require)=>{\n// ${relative(root, p)}\n${m.code}\n}`).join(',\n');
    out += `\n};const cache={};function require(id){if(cache[id])return cache[id];const exports={};cache[id]=exports;modules[id](exports,require);return exports;}return require(${main.id});})();\n`;
    if (esm)
        out += [...main.names].sort().map(n => `export const ${n}=__entry.${n};`).join('\n');
    return out;
}
export function build() {
    const css = read(resolve(root, 'apps/studio/studio.css'));
    const app = bundle(resolve(root, 'apps/studio/app.js'));
    const html = read(resolve(root, 'apps/studio/index.html')).replace('<link rel="stylesheet" href="./studio.css">', () => `<style>${css}</style>`).replace('<script type="module" src="./app.js"></script>', () => `<script>${app.replaceAll('</script', '<\\/script')}</script>`);
    if (html.includes('src="./app.js"') || html.includes('href="./studio.css"'))
        throw Error('Standalone entry replacements failed');
    put(resolve(root, 'dist/ChromaForge-Standalone.html'), html);
    put(resolve(root, 'dist/site/studio/index.html'), html);
    for (const name of ['core', 'geometry', 'paint', 'renderer', 'controls', 'collab']) {
        const code = bundle(resolve(root, `packages/${name}/src/index.js`), { esm: true });
        put(resolve(root, `packages/${name}/dist/index.js`), code);
        if (existsSync(resolve(root, `packages/${name}/index.d.ts`)))
            cpSync(resolve(root, `packages/${name}/index.d.ts`), resolve(root, `packages/${name}/dist/index.d.ts`));
        put(resolve(root, `dist/libraries/${name}.js`), code);
        put(resolve(root, `dist/site/libraries/${name}.js`), code);
    }
    if (existsSync(resolve(root, 'apps/site/index.html'))) {
        const html = read(resolve(root, 'apps/site/index.html')).replaceAll('../studio/', './studio/').replaceAll('../../examples/', './examples/');
        put(resolve(root, 'dist/site/index.html'), html);
        if (existsSync(resolve(root, 'apps/site/studio-preview.png')))
            cpSync(resolve(root, 'apps/site/studio-preview.png'), resolve(root, 'dist/site/studio-preview.png'));
        if (existsSync(resolve(root, 'apps/site/site.css')))
            cpSync(resolve(root, 'apps/site/site.css'), resolve(root, 'dist/site/site.css'));
        if (existsSync(resolve(root, 'apps/site/site.js')))
            put(resolve(root, 'dist/site/site.js'), bundle(resolve(root, 'apps/site/site.js')));
    }
    if (existsSync(resolve(root, 'examples/renderer.html'))) {
        const example = read(resolve(root, 'examples/renderer.html'));
        put(resolve(root, 'dist/site/examples/renderer.js'), bundle(resolve(root, 'examples/renderer.js')));
        put(resolve(root, 'dist/site/examples/renderer.html'), example);
    }
    console.log('Built standalone studio, static site and six self-contained ES module libraries.');
}
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url))
    build();
